### PR TITLE
[WIP] Installation on MARCONI (Cineca)

### LINKED ISSUE #5211: Installation on MARCONI (Cineca)
Hi!

I have HPC time on the MARCONI HPC, and I want to compile WarpX on the HPC. Will you help me make a guide for an optimal installation routine?

Many thanks, Johan

### PR DESCRIPTION
**Pull request by EZoni**
Close #5211.

- [ ] add profile script
- [ ] add submission script
- [ ] update docs

### CODE REVIEW

**Comment by EZoni** [comment]
@JohanKoelsenDeWit

Let's try to start simple and add complexity step by step.

I ping @WeiqunZhang here, who might be able to guide the installation more efficiently than me.

The first step would be to load the modules listed in the file currently added in this PR, `Tools/machines/marconi-cineca/marconi_cpu_warpx.profile.example`, and see what needs to be fixed/added for a _minimal_ WarpX build:
```
cmake --fresh -S . -DWarpX_DIMS="1;2;3" -DWarpX_OPENPMD=OFF -DWarpX_QED=OFF -B build
```

Please report here the output of the build and we iterate from there.

**Comment by JohanKoelsenDeWit** [comment]
> @JohanKoelsenDeWit
> 
> Let's try to start simple and add complexity step by step.
> 
> I ping @WeiqunZhang here, who might be able to guide the installation more efficiently than me.
> 
> The first step would be to load the modules listed in the file currently added in this PR, `Tools/machines/marconi-cineca/marconi_cpu_warpx.profile.example`, and see what needs to be fixed/added for a _minimal_ WarpX build:
> 
> ```
> cmake --fresh -S . -DWarpX_DIMS="1;2;3" -DWarpX_OPENPMD=OFF -DWarpX_QED=OFF -B build
> ```
> 
> Please report here the output of the build and we iterate from there.

Thank you kindly, Ezoni. I have imported the modules but cmake could not recognize --fresh. I believe this is due to the fact that the only available versions of cmake on MARCONI are cmake/3.18.2 and cmake/3.23.3. By removing the --fresh, it stated that I need 3.24.0 or higher.
To proceed, do you want me to request a newer version of cmake from the support on Marconi?

**Comment by EZoni** [comment]
Thanks, @JohanKoelsenDeWit.

We can definitely skip the `--fresh` option, but regardless of that we do require minimum version 3.24 indeed:
https://github.com/ECP-WarpX/WarpX/blob/dc68659c1b2d6a689f4b602bddd42f9099fb5928/CMakeLists.txt#L3
I do recommend inquiring with the MARCONI support and asking them if they can support CMake 3.24 (noting that the latest available version is now 3.31).

**Comment by JohanKoelsenDeWit** [comment]
> Thanks, @JohanKoelsenDeWit.
> 
> We can definitely skip the `--fresh` option, but regardless of that we do require minimum version 3.24 indeed:
> 
> https://github.com/ECP-WarpX/WarpX/blob/dc68659c1b2d6a689f4b602bddd42f9099fb5928/CMakeLists.txt#L3
> 
> I do recommend inquiring with the MARCONI support and asking them if they can support CMake 3.24 (noting that the latest available version is now 3.31).

Thanks @EZoni, I heard the MARCONI support, and they are sadly unable to install the newest version on CMake. They mentioned that version 22.06 of WarpX only required version 3.24 of CMake. Will we be able to use this version instead?

**Comment by EZoni** [comment]
I think the requirement of CMake 3.24+ was introduced in #5179, which was included in the 24.09 release.

So we can try to use the 24.08 release without going as far in the past as 22.06 and see if we can get something to work.

Not sure how/if we would document this in the main repo though, to be discussed internally with other maintainers. 

Do you want to check out the 24.08 release and see what errors come up when you try to configure and build WarpX with the minimal options above (except `--fresh`), so we can proceed with understanding which modules are missing and/or need a fix?
- Configure:
  ```console
  cmake -S . -DWarpX_DIMS="1;2;3" -DWarpX_OPENPMD=OFF -DWarpX_QED=OFF -B build
  ```
- Build:
  ```console
  cmake --build build -j 8
  ```

**Comment by JohanKoelsenDeWit** [comment]
> I think the requirement of CMake 3.24+ was introduced in #5179, which was included in the 24.09 release.
> 
> So we can try to use the 24.08 release without going as far in the past as 22.06 and see if we can get something to work.
> 
> Not sure how/if we would document this in the main repo though, to be discussed internally with other maintainers.
> 
> Do you want to check out the 24.08 release and see what errors come up when you try to configure and build WarpX with the minimal options above (except `--fresh`), so we can proceed with understanding which modules are missing and/or need a fix?
> 
>     * Configure:
>       ```
>       cmake -S . -DWarpX_DIMS="1;2;3" -DWarpX_OPENPMD=OFF -DWarpX_QED=OFF -B build
>       ```
> 
>     * Build:
>       ```
>       cmake --build build -j 8
>       ```

That sounds excellent. I managed to configure version 24.08 with `cmake -S . -DWarpX_DIMS="1;2;3" -DWarpX_OPENPMD=OFF -DWarpX_QED=OFF -B build`, but the compilation failed.

Attached is the error I received.
[build_output.txt](https://github.com/user-attachments/files/17393148/build_output.txt)

Thank you for your patience with this. :)

**Comment by EZoni** [comment]
I see errors like
```console
error: namespace "std" has no member "underlying_type_t"
```
but I'm not sure why.

We require at least C++17,
https://github.com/ECP-WarpX/WarpX/blob/09f9e8bad4ac109e167f255e29e961e3604dd5b7/CMakeLists.txt#L525-L546
so errors like the one above should not happen.

Could you also share the output of
- `module list`;
- the `cmake` configuration step;

so that we can look at the compiler info printed there?

Also, could you double check with the MARCONI support that they have an Intel compiler that supports C++17?

Based on what I see in the PR description of #2300 (where we introduced the C++17 requirement), I think you should be using at least Intel icpc 19.0.1+ (version 2021+ recommended). Although, if that is not the case, I would expect the configuration step to fail as well...

**Comment by JohanKoelsenDeWit** [comment]
Definitely! MARCONI is sadly down for the time being, but I will do it right away when I can access it again.

Best wishes, Johan


________________________________

**Comment by JohanKoelsenDeWit** [comment]
Hi again EZoni,

Sorry for the late reply. MARCONI is still not up and running, so I have decided to continue with WarpX on a HPC called Niflheim installed at the Technical University of Denmark. The compilation is successful, but I'm struggling with understanding the output format - the files are on binary form, but I'm trying to make the output format as a hdf5 by using OpenPMD. These are my lines for the cmake:
cmake -S . -B build   -DWarpX_OPENPMD=ON   -DWarpX_DIMS="1;2;3"   -DWarpX_QED=OFF  

[CMakeCache.txt](https://github.com/user-attachments/files/17937046/CMakeCache.txt)
The Cmake Cache is also attached here.

The outputs are stored in a diag directory as:
diag1000000  diag1000002  diag1000004  diag1000006  diag1000008  diag1000010  reducedfiles

As anticipated since I run an input file with: 
[test_run_gaussian_1d.txt](https://github.com/user-attachments/files/17937103/test_run_gaussian_1d.txt)
(normally a .py file but saved as a .txt file here to attach it).

Attached is a zip file of the diag1000000 folder:
[diag1000000.zip](https://github.com/user-attachments/files/17937069/diag1000000.zip)

I was hoping you could help me find my mistake? :) Thank you again for all your patience.

Best wishes, Johan

**Comment by JohanKoelsenDeWit** [comment]
> Hi again EZoni,
> 
> Sorry for the late reply. MARCONI is still not up and running, so I have decided to continue with WarpX on a HPC called Niflheim installed at the Technical University of Denmark. The compilation is successful, but I'm struggling with understanding the output format - the files are on binary form, but I'm trying to make the output format as a hdf5 by using OpenPMD. These are my lines for the cmake: cmake -S . -B build -DWarpX_OPENPMD=ON -DWarpX_DIMS="1;2;3" -DWarpX_QED=OFF
> 
> [CMakeCache.txt](https://github.com/user-attachments/files/17937046/CMakeCache.txt) The Cmake Cache is also attached here.
> 
> The outputs are stored in a diag directory as: diag1000000 diag1000002 diag1000004 diag1000006 diag1000008 diag1000010 reducedfiles
> 
> As anticipated since I run an input file with: [test_run_gaussian_1d.txt](https://github.com/user-attachments/files/17937103/test_run_gaussian_1d.txt) (normally a .py file but saved as a .txt file here to attach it).
> 
> Attached is a zip file of the diag1000000 folder: [diag1000000.zip](https://github.com/user-attachments/files/17937069/diag1000000.zip)
> 
> I was hoping you could help me find my mistake? :) Thank you again for all your patience.
> 
> Best wishes, Johan

Dear EZoni, I found my error! I had missed the setting: <diag_name>.format (string optional, default plotfile), and after setting it to openpmd, I see that the files are a h5 format as wanted! Sorry for the inconvenience.

**Comment by EZoni** [comment]
@JohanKoelsenDeWit 

Thank you for your feedback. Since you will not continue the installation of WarpX on MARCONI, I will close this PR without merging for now. We can always resume this work in the future, if needed.

**Comment by EZoni** [comment]
Closing this PR for now, as explained in https://github.com/ECP-WarpX/WarpX/pull/5377#issuecomment-2518753469.
